/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkerRouteImport } from './routes/worker'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginChoiceRouteImport } from './routes/login-choice'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ContractorRouteImport } from './routes/contractor'
import { Route as AuthChoiceRouteImport } from './routes/auth-choice'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkerIndexRouteImport } from './routes/worker.index'
import { Route as ContractorIndexRouteImport } from './routes/contractor.index'
import { Route as WorkerSettingsRouteImport } from './routes/worker.settings'
import { Route as WorkerProfileRouteImport } from './routes/worker.profile'
import { Route as WorkerPrivacyRouteImport } from './routes/worker.privacy'
import { Route as WorkerNotificationsRouteImport } from './routes/worker.notifications'
import { Route as WorkerMessagesRouteImport } from './routes/worker.messages'
import { Route as WorkerHistoryRouteImport } from './routes/worker.history'
import { Route as WorkerHelpRouteImport } from './routes/worker.help'
import { Route as WorkerEarningsRouteImport } from './routes/worker.earnings'
import { Route as WorkerChangePasswordRouteImport } from './routes/worker.change-password'
import { Route as WorkerAcceptedRouteImport } from './routes/worker.accepted'
import { Route as ContractorWorkersRouteImport } from './routes/contractor.workers'
import { Route as ContractorWorkerDetailsRouteImport } from './routes/contractor.worker-details'
import { Route as ContractorSettingsRouteImport } from './routes/contractor.settings'
import { Route as ContractorProfileRouteImport } from './routes/contractor.profile'
import { Route as ContractorPrivacyRouteImport } from './routes/contractor.privacy'
import { Route as ContractorPostRouteImport } from './routes/contractor.post'
import { Route as ContractorPaymentsRouteImport } from './routes/contractor.payments'
import { Route as ContractorNotificationsRouteImport } from './routes/contractor.notifications'
import { Route as ContractorMessagesRouteImport } from './routes/contractor.messages'
import { Route as ContractorHelpRouteImport } from './routes/contractor.help'
import { Route as ContractorChangePasswordRouteImport } from './routes/contractor.change-password'
import { Route as ContractorAnalyticsRouteImport } from './routes/contractor.analytics'
import { Route as ContractorActiveRouteImport } from './routes/contractor.active'
import { Route as WorkerJobsIndexRouteImport } from './routes/worker.jobs.index'
import { Route as ContractorApplicationsIndexRouteImport } from './routes/contractor.applications.index'
import { Route as WorkerJobsJobIdRouteImport } from './routes/worker.jobs.$jobId'
import { Route as WorkerEarningsTotalRouteImport } from './routes/worker.earnings.total'
import { Route as WorkerEarningsPendingRouteImport } from './routes/worker.earnings.pending'
import { Route as WorkerEarningsMonthlyRouteImport } from './routes/worker.earnings.monthly'
import { Route as WorkerEarningsCompletedRouteImport } from './routes/worker.earnings.completed'
import { Route as ContractorPaymentsSuccessRouteImport } from './routes/contractor.payments.success'
import { Route as ContractorApplicationsHiredRouteImport } from './routes/contractor.applications.hired'
import { Route as ContractorApplicationsDeclinedRouteImport } from './routes/contractor.applications.declined'
import { Route as ContractorApplicationsApplicationIdRouteImport } from './routes/contractor.applications.$applicationId'
import { Route as WorkerJobsJobIdIndexRouteImport } from './routes/worker.jobs.$jobId.index'
import { Route as WorkerJobsJobIdApplyRouteImport } from './routes/worker.jobs.$jobId.apply'
import { Route as ContractorJobsJobIdManageRouteImport } from './routes/contractor.jobs.$jobId.manage'

const WorkerRoute = WorkerRouteImport.update({
  id: '/worker',
  path: '/worker',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginChoiceRoute = LoginChoiceRouteImport.update({
  id: '/login-choice',
  path: '/login-choice',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractorRoute = ContractorRouteImport.update({
  id: '/contractor',
  path: '/contractor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthChoiceRoute = AuthChoiceRouteImport.update({
  id: '/auth-choice',
  path: '/auth-choice',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkerIndexRoute = WorkerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkerRoute,
} as any)
const ContractorIndexRoute = ContractorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ContractorRoute,
} as any)
const WorkerSettingsRoute = WorkerSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WorkerRoute,
} as any)
const WorkerProfileRoute = WorkerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => WorkerRoute,
} as any)
const WorkerPrivacyRoute = WorkerPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => WorkerRoute,
} as any)
const WorkerNotificationsRoute = WorkerNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => WorkerRoute,
} as any)
const WorkerMessagesRoute = WorkerMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => WorkerRoute,
} as any)
const WorkerHistoryRoute = WorkerHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => WorkerRoute,
} as any)
const WorkerHelpRoute = WorkerHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => WorkerRoute,
} as any)
const WorkerEarningsRoute = WorkerEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => WorkerRoute,
} as any)
const WorkerChangePasswordRoute = WorkerChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => WorkerRoute,
} as any)
const WorkerAcceptedRoute = WorkerAcceptedRouteImport.update({
  id: '/accepted',
  path: '/accepted',
  getParentRoute: () => WorkerRoute,
} as any)
const ContractorWorkersRoute = ContractorWorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => ContractorRoute,
} as any)
const ContractorWorkerDetailsRoute = ContractorWorkerDetailsRouteImport.update({
  id: '/worker-details',
  path: '/worker-details',
  getParentRoute: () => ContractorRoute,
} as any)
const ContractorSettingsRoute = ContractorSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ContractorRoute,
} as any)
const ContractorProfileRoute = ContractorProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ContractorRoute,
} as any)
const ContractorPrivacyRoute = ContractorPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => ContractorRoute,
} as any)
const ContractorPostRoute = ContractorPostRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => ContractorRoute,
} as any)
const ContractorPaymentsRoute = ContractorPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => ContractorRoute,
} as any)
const ContractorNotificationsRoute = ContractorNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ContractorRoute,
} as any)
const ContractorMessagesRoute = ContractorMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => ContractorRoute,
} as any)
const ContractorHelpRoute = ContractorHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => ContractorRoute,
} as any)
const ContractorChangePasswordRoute =
  ContractorChangePasswordRouteImport.update({
    id: '/change-password',
    path: '/change-password',
    getParentRoute: () => ContractorRoute,
  } as any)
const ContractorAnalyticsRoute = ContractorAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => ContractorRoute,
} as any)
const ContractorActiveRoute = ContractorActiveRouteImport.update({
  id: '/active',
  path: '/active',
  getParentRoute: () => ContractorRoute,
} as any)
const WorkerJobsIndexRoute = WorkerJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => WorkerRoute,
} as any)
const ContractorApplicationsIndexRoute =
  ContractorApplicationsIndexRouteImport.update({
    id: '/applications/',
    path: '/applications/',
    getParentRoute: () => ContractorRoute,
  } as any)
const WorkerJobsJobIdRoute = WorkerJobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => WorkerRoute,
} as any)
const WorkerEarningsTotalRoute = WorkerEarningsTotalRouteImport.update({
  id: '/total',
  path: '/total',
  getParentRoute: () => WorkerEarningsRoute,
} as any)
const WorkerEarningsPendingRoute = WorkerEarningsPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => WorkerEarningsRoute,
} as any)
const WorkerEarningsMonthlyRoute = WorkerEarningsMonthlyRouteImport.update({
  id: '/monthly',
  path: '/monthly',
  getParentRoute: () => WorkerEarningsRoute,
} as any)
const WorkerEarningsCompletedRoute = WorkerEarningsCompletedRouteImport.update({
  id: '/completed',
  path: '/completed',
  getParentRoute: () => WorkerEarningsRoute,
} as any)
const ContractorPaymentsSuccessRoute =
  ContractorPaymentsSuccessRouteImport.update({
    id: '/success',
    path: '/success',
    getParentRoute: () => ContractorPaymentsRoute,
  } as any)
const ContractorApplicationsHiredRoute =
  ContractorApplicationsHiredRouteImport.update({
    id: '/applications/hired',
    path: '/applications/hired',
    getParentRoute: () => ContractorRoute,
  } as any)
const ContractorApplicationsDeclinedRoute =
  ContractorApplicationsDeclinedRouteImport.update({
    id: '/applications/declined',
    path: '/applications/declined',
    getParentRoute: () => ContractorRoute,
  } as any)
const ContractorApplicationsApplicationIdRoute =
  ContractorApplicationsApplicationIdRouteImport.update({
    id: '/applications/$applicationId',
    path: '/applications/$applicationId',
    getParentRoute: () => ContractorRoute,
  } as any)
const WorkerJobsJobIdIndexRoute = WorkerJobsJobIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkerJobsJobIdRoute,
} as any)
const WorkerJobsJobIdApplyRoute = WorkerJobsJobIdApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => WorkerJobsJobIdRoute,
} as any)
const ContractorJobsJobIdManageRoute =
  ContractorJobsJobIdManageRouteImport.update({
    id: '/jobs/$jobId/manage',
    path: '/jobs/$jobId/manage',
    getParentRoute: () => ContractorRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth-choice': typeof AuthChoiceRoute
  '/contractor': typeof ContractorRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/login-choice': typeof LoginChoiceRoute
  '/register': typeof RegisterRoute
  '/signup': typeof SignupRoute
  '/welcome': typeof WelcomeRoute
  '/worker': typeof WorkerRouteWithChildren
  '/contractor/active': typeof ContractorActiveRoute
  '/contractor/analytics': typeof ContractorAnalyticsRoute
  '/contractor/change-password': typeof ContractorChangePasswordRoute
  '/contractor/help': typeof ContractorHelpRoute
  '/contractor/messages': typeof ContractorMessagesRoute
  '/contractor/notifications': typeof ContractorNotificationsRoute
  '/contractor/payments': typeof ContractorPaymentsRouteWithChildren
  '/contractor/post': typeof ContractorPostRoute
  '/contractor/privacy': typeof ContractorPrivacyRoute
  '/contractor/profile': typeof ContractorProfileRoute
  '/contractor/settings': typeof ContractorSettingsRoute
  '/contractor/worker-details': typeof ContractorWorkerDetailsRoute
  '/contractor/workers': typeof ContractorWorkersRoute
  '/worker/accepted': typeof WorkerAcceptedRoute
  '/worker/change-password': typeof WorkerChangePasswordRoute
  '/worker/earnings': typeof WorkerEarningsRouteWithChildren
  '/worker/help': typeof WorkerHelpRoute
  '/worker/history': typeof WorkerHistoryRoute
  '/worker/messages': typeof WorkerMessagesRoute
  '/worker/notifications': typeof WorkerNotificationsRoute
  '/worker/privacy': typeof WorkerPrivacyRoute
  '/worker/profile': typeof WorkerProfileRoute
  '/worker/settings': typeof WorkerSettingsRoute
  '/contractor/': typeof ContractorIndexRoute
  '/worker/': typeof WorkerIndexRoute
  '/contractor/applications/$applicationId': typeof ContractorApplicationsApplicationIdRoute
  '/contractor/applications/declined': typeof ContractorApplicationsDeclinedRoute
  '/contractor/applications/hired': typeof ContractorApplicationsHiredRoute
  '/contractor/payments/success': typeof ContractorPaymentsSuccessRoute
  '/worker/earnings/completed': typeof WorkerEarningsCompletedRoute
  '/worker/earnings/monthly': typeof WorkerEarningsMonthlyRoute
  '/worker/earnings/pending': typeof WorkerEarningsPendingRoute
  '/worker/earnings/total': typeof WorkerEarningsTotalRoute
  '/worker/jobs/$jobId': typeof WorkerJobsJobIdRouteWithChildren
  '/contractor/applications/': typeof ContractorApplicationsIndexRoute
  '/worker/jobs/': typeof WorkerJobsIndexRoute
  '/contractor/jobs/$jobId/manage': typeof ContractorJobsJobIdManageRoute
  '/worker/jobs/$jobId/apply': typeof WorkerJobsJobIdApplyRoute
  '/worker/jobs/$jobId/': typeof WorkerJobsJobIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth-choice': typeof AuthChoiceRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/login-choice': typeof LoginChoiceRoute
  '/register': typeof RegisterRoute
  '/signup': typeof SignupRoute
  '/welcome': typeof WelcomeRoute
  '/contractor/active': typeof ContractorActiveRoute
  '/contractor/analytics': typeof ContractorAnalyticsRoute
  '/contractor/change-password': typeof ContractorChangePasswordRoute
  '/contractor/help': typeof ContractorHelpRoute
  '/contractor/messages': typeof ContractorMessagesRoute
  '/contractor/notifications': typeof ContractorNotificationsRoute
  '/contractor/payments': typeof ContractorPaymentsRouteWithChildren
  '/contractor/post': typeof ContractorPostRoute
  '/contractor/privacy': typeof ContractorPrivacyRoute
  '/contractor/profile': typeof ContractorProfileRoute
  '/contractor/settings': typeof ContractorSettingsRoute
  '/contractor/worker-details': typeof ContractorWorkerDetailsRoute
  '/contractor/workers': typeof ContractorWorkersRoute
  '/worker/accepted': typeof WorkerAcceptedRoute
  '/worker/change-password': typeof WorkerChangePasswordRoute
  '/worker/earnings': typeof WorkerEarningsRouteWithChildren
  '/worker/help': typeof WorkerHelpRoute
  '/worker/history': typeof WorkerHistoryRoute
  '/worker/messages': typeof WorkerMessagesRoute
  '/worker/notifications': typeof WorkerNotificationsRoute
  '/worker/privacy': typeof WorkerPrivacyRoute
  '/worker/profile': typeof WorkerProfileRoute
  '/worker/settings': typeof WorkerSettingsRoute
  '/contractor': typeof ContractorIndexRoute
  '/worker': typeof WorkerIndexRoute
  '/contractor/applications/$applicationId': typeof ContractorApplicationsApplicationIdRoute
  '/contractor/applications/declined': typeof ContractorApplicationsDeclinedRoute
  '/contractor/applications/hired': typeof ContractorApplicationsHiredRoute
  '/contractor/payments/success': typeof ContractorPaymentsSuccessRoute
  '/worker/earnings/completed': typeof WorkerEarningsCompletedRoute
  '/worker/earnings/monthly': typeof WorkerEarningsMonthlyRoute
  '/worker/earnings/pending': typeof WorkerEarningsPendingRoute
  '/worker/earnings/total': typeof WorkerEarningsTotalRoute
  '/contractor/applications': typeof ContractorApplicationsIndexRoute
  '/worker/jobs': typeof WorkerJobsIndexRoute
  '/contractor/jobs/$jobId/manage': typeof ContractorJobsJobIdManageRoute
  '/worker/jobs/$jobId/apply': typeof WorkerJobsJobIdApplyRoute
  '/worker/jobs/$jobId': typeof WorkerJobsJobIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth-choice': typeof AuthChoiceRoute
  '/contractor': typeof ContractorRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/login-choice': typeof LoginChoiceRoute
  '/register': typeof RegisterRoute
  '/signup': typeof SignupRoute
  '/welcome': typeof WelcomeRoute
  '/worker': typeof WorkerRouteWithChildren
  '/contractor/active': typeof ContractorActiveRoute
  '/contractor/analytics': typeof ContractorAnalyticsRoute
  '/contractor/change-password': typeof ContractorChangePasswordRoute
  '/contractor/help': typeof ContractorHelpRoute
  '/contractor/messages': typeof ContractorMessagesRoute
  '/contractor/notifications': typeof ContractorNotificationsRoute
  '/contractor/payments': typeof ContractorPaymentsRouteWithChildren
  '/contractor/post': typeof ContractorPostRoute
  '/contractor/privacy': typeof ContractorPrivacyRoute
  '/contractor/profile': typeof ContractorProfileRoute
  '/contractor/settings': typeof ContractorSettingsRoute
  '/contractor/worker-details': typeof ContractorWorkerDetailsRoute
  '/contractor/workers': typeof ContractorWorkersRoute
  '/worker/accepted': typeof WorkerAcceptedRoute
  '/worker/change-password': typeof WorkerChangePasswordRoute
  '/worker/earnings': typeof WorkerEarningsRouteWithChildren
  '/worker/help': typeof WorkerHelpRoute
  '/worker/history': typeof WorkerHistoryRoute
  '/worker/messages': typeof WorkerMessagesRoute
  '/worker/notifications': typeof WorkerNotificationsRoute
  '/worker/privacy': typeof WorkerPrivacyRoute
  '/worker/profile': typeof WorkerProfileRoute
  '/worker/settings': typeof WorkerSettingsRoute
  '/contractor/': typeof ContractorIndexRoute
  '/worker/': typeof WorkerIndexRoute
  '/contractor/applications/$applicationId': typeof ContractorApplicationsApplicationIdRoute
  '/contractor/applications/declined': typeof ContractorApplicationsDeclinedRoute
  '/contractor/applications/hired': typeof ContractorApplicationsHiredRoute
  '/contractor/payments/success': typeof ContractorPaymentsSuccessRoute
  '/worker/earnings/completed': typeof WorkerEarningsCompletedRoute
  '/worker/earnings/monthly': typeof WorkerEarningsMonthlyRoute
  '/worker/earnings/pending': typeof WorkerEarningsPendingRoute
  '/worker/earnings/total': typeof WorkerEarningsTotalRoute
  '/worker/jobs/$jobId': typeof WorkerJobsJobIdRouteWithChildren
  '/contractor/applications/': typeof ContractorApplicationsIndexRoute
  '/worker/jobs/': typeof WorkerJobsIndexRoute
  '/contractor/jobs/$jobId/manage': typeof ContractorJobsJobIdManageRoute
  '/worker/jobs/$jobId/apply': typeof WorkerJobsJobIdApplyRoute
  '/worker/jobs/$jobId/': typeof WorkerJobsJobIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth-choice'
    | '/contractor'
    | '/forgot-password'
    | '/login'
    | '/login-choice'
    | '/register'
    | '/signup'
    | '/welcome'
    | '/worker'
    | '/contractor/active'
    | '/contractor/analytics'
    | '/contractor/change-password'
    | '/contractor/help'
    | '/contractor/messages'
    | '/contractor/notifications'
    | '/contractor/payments'
    | '/contractor/post'
    | '/contractor/privacy'
    | '/contractor/profile'
    | '/contractor/settings'
    | '/contractor/worker-details'
    | '/contractor/workers'
    | '/worker/accepted'
    | '/worker/change-password'
    | '/worker/earnings'
    | '/worker/help'
    | '/worker/history'
    | '/worker/messages'
    | '/worker/notifications'
    | '/worker/privacy'
    | '/worker/profile'
    | '/worker/settings'
    | '/contractor/'
    | '/worker/'
    | '/contractor/applications/$applicationId'
    | '/contractor/applications/declined'
    | '/contractor/applications/hired'
    | '/contractor/payments/success'
    | '/worker/earnings/completed'
    | '/worker/earnings/monthly'
    | '/worker/earnings/pending'
    | '/worker/earnings/total'
    | '/worker/jobs/$jobId'
    | '/contractor/applications/'
    | '/worker/jobs/'
    | '/contractor/jobs/$jobId/manage'
    | '/worker/jobs/$jobId/apply'
    | '/worker/jobs/$jobId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth-choice'
    | '/forgot-password'
    | '/login'
    | '/login-choice'
    | '/register'
    | '/signup'
    | '/welcome'
    | '/contractor/active'
    | '/contractor/analytics'
    | '/contractor/change-password'
    | '/contractor/help'
    | '/contractor/messages'
    | '/contractor/notifications'
    | '/contractor/payments'
    | '/contractor/post'
    | '/contractor/privacy'
    | '/contractor/profile'
    | '/contractor/settings'
    | '/contractor/worker-details'
    | '/contractor/workers'
    | '/worker/accepted'
    | '/worker/change-password'
    | '/worker/earnings'
    | '/worker/help'
    | '/worker/history'
    | '/worker/messages'
    | '/worker/notifications'
    | '/worker/privacy'
    | '/worker/profile'
    | '/worker/settings'
    | '/contractor'
    | '/worker'
    | '/contractor/applications/$applicationId'
    | '/contractor/applications/declined'
    | '/contractor/applications/hired'
    | '/contractor/payments/success'
    | '/worker/earnings/completed'
    | '/worker/earnings/monthly'
    | '/worker/earnings/pending'
    | '/worker/earnings/total'
    | '/contractor/applications'
    | '/worker/jobs'
    | '/contractor/jobs/$jobId/manage'
    | '/worker/jobs/$jobId/apply'
    | '/worker/jobs/$jobId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth-choice'
    | '/contractor'
    | '/forgot-password'
    | '/login'
    | '/login-choice'
    | '/register'
    | '/signup'
    | '/welcome'
    | '/worker'
    | '/contractor/active'
    | '/contractor/analytics'
    | '/contractor/change-password'
    | '/contractor/help'
    | '/contractor/messages'
    | '/contractor/notifications'
    | '/contractor/payments'
    | '/contractor/post'
    | '/contractor/privacy'
    | '/contractor/profile'
    | '/contractor/settings'
    | '/contractor/worker-details'
    | '/contractor/workers'
    | '/worker/accepted'
    | '/worker/change-password'
    | '/worker/earnings'
    | '/worker/help'
    | '/worker/history'
    | '/worker/messages'
    | '/worker/notifications'
    | '/worker/privacy'
    | '/worker/profile'
    | '/worker/settings'
    | '/contractor/'
    | '/worker/'
    | '/contractor/applications/$applicationId'
    | '/contractor/applications/declined'
    | '/contractor/applications/hired'
    | '/contractor/payments/success'
    | '/worker/earnings/completed'
    | '/worker/earnings/monthly'
    | '/worker/earnings/pending'
    | '/worker/earnings/total'
    | '/worker/jobs/$jobId'
    | '/contractor/applications/'
    | '/worker/jobs/'
    | '/contractor/jobs/$jobId/manage'
    | '/worker/jobs/$jobId/apply'
    | '/worker/jobs/$jobId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthChoiceRoute: typeof AuthChoiceRoute
  ContractorRoute: typeof ContractorRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  LoginChoiceRoute: typeof LoginChoiceRoute
  RegisterRoute: typeof RegisterRoute
  SignupRoute: typeof SignupRoute
  WelcomeRoute: typeof WelcomeRoute
  WorkerRoute: typeof WorkerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/worker': {
      id: '/worker'
      path: '/worker'
      fullPath: '/worker'
      preLoaderRoute: typeof WorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login-choice': {
      id: '/login-choice'
      path: '/login-choice'
      fullPath: '/login-choice'
      preLoaderRoute: typeof LoginChoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contractor': {
      id: '/contractor'
      path: '/contractor'
      fullPath: '/contractor'
      preLoaderRoute: typeof ContractorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-choice': {
      id: '/auth-choice'
      path: '/auth-choice'
      fullPath: '/auth-choice'
      preLoaderRoute: typeof AuthChoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worker/': {
      id: '/worker/'
      path: '/'
      fullPath: '/worker/'
      preLoaderRoute: typeof WorkerIndexRouteImport
      parentRoute: typeof WorkerRoute
    }
    '/contractor/': {
      id: '/contractor/'
      path: '/'
      fullPath: '/contractor/'
      preLoaderRoute: typeof ContractorIndexRouteImport
      parentRoute: typeof ContractorRoute
    }
    '/worker/settings': {
      id: '/worker/settings'
      path: '/settings'
      fullPath: '/worker/settings'
      preLoaderRoute: typeof WorkerSettingsRouteImport
      parentRoute: typeof WorkerRoute
    }
    '/worker/profile': {
      id: '/worker/profile'
      path: '/profile'
      fullPath: '/worker/profile'
      preLoaderRoute: typeof WorkerProfileRouteImport
      parentRoute: typeof WorkerRoute
    }
    '/worker/privacy': {
      id: '/worker/privacy'
      path: '/privacy'
      fullPath: '/worker/privacy'
      preLoaderRoute: typeof WorkerPrivacyRouteImport
      parentRoute: typeof WorkerRoute
    }
    '/worker/notifications': {
      id: '/worker/notifications'
      path: '/notifications'
      fullPath: '/worker/notifications'
      preLoaderRoute: typeof WorkerNotificationsRouteImport
      parentRoute: typeof WorkerRoute
    }
    '/worker/messages': {
      id: '/worker/messages'
      path: '/messages'
      fullPath: '/worker/messages'
      preLoaderRoute: typeof WorkerMessagesRouteImport
      parentRoute: typeof WorkerRoute
    }
    '/worker/history': {
      id: '/worker/history'
      path: '/history'
      fullPath: '/worker/history'
      preLoaderRoute: typeof WorkerHistoryRouteImport
      parentRoute: typeof WorkerRoute
    }
    '/worker/help': {
      id: '/worker/help'
      path: '/help'
      fullPath: '/worker/help'
      preLoaderRoute: typeof WorkerHelpRouteImport
      parentRoute: typeof WorkerRoute
    }
    '/worker/earnings': {
      id: '/worker/earnings'
      path: '/earnings'
      fullPath: '/worker/earnings'
      preLoaderRoute: typeof WorkerEarningsRouteImport
      parentRoute: typeof WorkerRoute
    }
    '/worker/change-password': {
      id: '/worker/change-password'
      path: '/change-password'
      fullPath: '/worker/change-password'
      preLoaderRoute: typeof WorkerChangePasswordRouteImport
      parentRoute: typeof WorkerRoute
    }
    '/worker/accepted': {
      id: '/worker/accepted'
      path: '/accepted'
      fullPath: '/worker/accepted'
      preLoaderRoute: typeof WorkerAcceptedRouteImport
      parentRoute: typeof WorkerRoute
    }
    '/contractor/workers': {
      id: '/contractor/workers'
      path: '/workers'
      fullPath: '/contractor/workers'
      preLoaderRoute: typeof ContractorWorkersRouteImport
      parentRoute: typeof ContractorRoute
    }
    '/contractor/worker-details': {
      id: '/contractor/worker-details'
      path: '/worker-details'
      fullPath: '/contractor/worker-details'
      preLoaderRoute: typeof ContractorWorkerDetailsRouteImport
      parentRoute: typeof ContractorRoute
    }
    '/contractor/settings': {
      id: '/contractor/settings'
      path: '/settings'
      fullPath: '/contractor/settings'
      preLoaderRoute: typeof ContractorSettingsRouteImport
      parentRoute: typeof ContractorRoute
    }
    '/contractor/profile': {
      id: '/contractor/profile'
      path: '/profile'
      fullPath: '/contractor/profile'
      preLoaderRoute: typeof ContractorProfileRouteImport
      parentRoute: typeof ContractorRoute
    }
    '/contractor/privacy': {
      id: '/contractor/privacy'
      path: '/privacy'
      fullPath: '/contractor/privacy'
      preLoaderRoute: typeof ContractorPrivacyRouteImport
      parentRoute: typeof ContractorRoute
    }
    '/contractor/post': {
      id: '/contractor/post'
      path: '/post'
      fullPath: '/contractor/post'
      preLoaderRoute: typeof ContractorPostRouteImport
      parentRoute: typeof ContractorRoute
    }
    '/contractor/payments': {
      id: '/contractor/payments'
      path: '/payments'
      fullPath: '/contractor/payments'
      preLoaderRoute: typeof ContractorPaymentsRouteImport
      parentRoute: typeof ContractorRoute
    }
    '/contractor/notifications': {
      id: '/contractor/notifications'
      path: '/notifications'
      fullPath: '/contractor/notifications'
      preLoaderRoute: typeof ContractorNotificationsRouteImport
      parentRoute: typeof ContractorRoute
    }
    '/contractor/messages': {
      id: '/contractor/messages'
      path: '/messages'
      fullPath: '/contractor/messages'
      preLoaderRoute: typeof ContractorMessagesRouteImport
      parentRoute: typeof ContractorRoute
    }
    '/contractor/help': {
      id: '/contractor/help'
      path: '/help'
      fullPath: '/contractor/help'
      preLoaderRoute: typeof ContractorHelpRouteImport
      parentRoute: typeof ContractorRoute
    }
    '/contractor/change-password': {
      id: '/contractor/change-password'
      path: '/change-password'
      fullPath: '/contractor/change-password'
      preLoaderRoute: typeof ContractorChangePasswordRouteImport
      parentRoute: typeof ContractorRoute
    }
    '/contractor/analytics': {
      id: '/contractor/analytics'
      path: '/analytics'
      fullPath: '/contractor/analytics'
      preLoaderRoute: typeof ContractorAnalyticsRouteImport
      parentRoute: typeof ContractorRoute
    }
    '/contractor/active': {
      id: '/contractor/active'
      path: '/active'
      fullPath: '/contractor/active'
      preLoaderRoute: typeof ContractorActiveRouteImport
      parentRoute: typeof ContractorRoute
    }
    '/worker/jobs/': {
      id: '/worker/jobs/'
      path: '/jobs'
      fullPath: '/worker/jobs/'
      preLoaderRoute: typeof WorkerJobsIndexRouteImport
      parentRoute: typeof WorkerRoute
    }
    '/contractor/applications/': {
      id: '/contractor/applications/'
      path: '/applications'
      fullPath: '/contractor/applications/'
      preLoaderRoute: typeof ContractorApplicationsIndexRouteImport
      parentRoute: typeof ContractorRoute
    }
    '/worker/jobs/$jobId': {
      id: '/worker/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/worker/jobs/$jobId'
      preLoaderRoute: typeof WorkerJobsJobIdRouteImport
      parentRoute: typeof WorkerRoute
    }
    '/worker/earnings/total': {
      id: '/worker/earnings/total'
      path: '/total'
      fullPath: '/worker/earnings/total'
      preLoaderRoute: typeof WorkerEarningsTotalRouteImport
      parentRoute: typeof WorkerEarningsRoute
    }
    '/worker/earnings/pending': {
      id: '/worker/earnings/pending'
      path: '/pending'
      fullPath: '/worker/earnings/pending'
      preLoaderRoute: typeof WorkerEarningsPendingRouteImport
      parentRoute: typeof WorkerEarningsRoute
    }
    '/worker/earnings/monthly': {
      id: '/worker/earnings/monthly'
      path: '/monthly'
      fullPath: '/worker/earnings/monthly'
      preLoaderRoute: typeof WorkerEarningsMonthlyRouteImport
      parentRoute: typeof WorkerEarningsRoute
    }
    '/worker/earnings/completed': {
      id: '/worker/earnings/completed'
      path: '/completed'
      fullPath: '/worker/earnings/completed'
      preLoaderRoute: typeof WorkerEarningsCompletedRouteImport
      parentRoute: typeof WorkerEarningsRoute
    }
    '/contractor/payments/success': {
      id: '/contractor/payments/success'
      path: '/success'
      fullPath: '/contractor/payments/success'
      preLoaderRoute: typeof ContractorPaymentsSuccessRouteImport
      parentRoute: typeof ContractorPaymentsRoute
    }
    '/contractor/applications/hired': {
      id: '/contractor/applications/hired'
      path: '/applications/hired'
      fullPath: '/contractor/applications/hired'
      preLoaderRoute: typeof ContractorApplicationsHiredRouteImport
      parentRoute: typeof ContractorRoute
    }
    '/contractor/applications/declined': {
      id: '/contractor/applications/declined'
      path: '/applications/declined'
      fullPath: '/contractor/applications/declined'
      preLoaderRoute: typeof ContractorApplicationsDeclinedRouteImport
      parentRoute: typeof ContractorRoute
    }
    '/contractor/applications/$applicationId': {
      id: '/contractor/applications/$applicationId'
      path: '/applications/$applicationId'
      fullPath: '/contractor/applications/$applicationId'
      preLoaderRoute: typeof ContractorApplicationsApplicationIdRouteImport
      parentRoute: typeof ContractorRoute
    }
    '/worker/jobs/$jobId/': {
      id: '/worker/jobs/$jobId/'
      path: '/'
      fullPath: '/worker/jobs/$jobId/'
      preLoaderRoute: typeof WorkerJobsJobIdIndexRouteImport
      parentRoute: typeof WorkerJobsJobIdRoute
    }
    '/worker/jobs/$jobId/apply': {
      id: '/worker/jobs/$jobId/apply'
      path: '/apply'
      fullPath: '/worker/jobs/$jobId/apply'
      preLoaderRoute: typeof WorkerJobsJobIdApplyRouteImport
      parentRoute: typeof WorkerJobsJobIdRoute
    }
    '/contractor/jobs/$jobId/manage': {
      id: '/contractor/jobs/$jobId/manage'
      path: '/jobs/$jobId/manage'
      fullPath: '/contractor/jobs/$jobId/manage'
      preLoaderRoute: typeof ContractorJobsJobIdManageRouteImport
      parentRoute: typeof ContractorRoute
    }
  }
}

interface ContractorPaymentsRouteChildren {
  ContractorPaymentsSuccessRoute: typeof ContractorPaymentsSuccessRoute
}

const ContractorPaymentsRouteChildren: ContractorPaymentsRouteChildren = {
  ContractorPaymentsSuccessRoute: ContractorPaymentsSuccessRoute,
}

const ContractorPaymentsRouteWithChildren =
  ContractorPaymentsRoute._addFileChildren(ContractorPaymentsRouteChildren)

interface ContractorRouteChildren {
  ContractorActiveRoute: typeof ContractorActiveRoute
  ContractorAnalyticsRoute: typeof ContractorAnalyticsRoute
  ContractorChangePasswordRoute: typeof ContractorChangePasswordRoute
  ContractorHelpRoute: typeof ContractorHelpRoute
  ContractorMessagesRoute: typeof ContractorMessagesRoute
  ContractorNotificationsRoute: typeof ContractorNotificationsRoute
  ContractorPaymentsRoute: typeof ContractorPaymentsRouteWithChildren
  ContractorPostRoute: typeof ContractorPostRoute
  ContractorPrivacyRoute: typeof ContractorPrivacyRoute
  ContractorProfileRoute: typeof ContractorProfileRoute
  ContractorSettingsRoute: typeof ContractorSettingsRoute
  ContractorWorkerDetailsRoute: typeof ContractorWorkerDetailsRoute
  ContractorWorkersRoute: typeof ContractorWorkersRoute
  ContractorIndexRoute: typeof ContractorIndexRoute
  ContractorApplicationsApplicationIdRoute: typeof ContractorApplicationsApplicationIdRoute
  ContractorApplicationsDeclinedRoute: typeof ContractorApplicationsDeclinedRoute
  ContractorApplicationsHiredRoute: typeof ContractorApplicationsHiredRoute
  ContractorApplicationsIndexRoute: typeof ContractorApplicationsIndexRoute
  ContractorJobsJobIdManageRoute: typeof ContractorJobsJobIdManageRoute
}

const ContractorRouteChildren: ContractorRouteChildren = {
  ContractorActiveRoute: ContractorActiveRoute,
  ContractorAnalyticsRoute: ContractorAnalyticsRoute,
  ContractorChangePasswordRoute: ContractorChangePasswordRoute,
  ContractorHelpRoute: ContractorHelpRoute,
  ContractorMessagesRoute: ContractorMessagesRoute,
  ContractorNotificationsRoute: ContractorNotificationsRoute,
  ContractorPaymentsRoute: ContractorPaymentsRouteWithChildren,
  ContractorPostRoute: ContractorPostRoute,
  ContractorPrivacyRoute: ContractorPrivacyRoute,
  ContractorProfileRoute: ContractorProfileRoute,
  ContractorSettingsRoute: ContractorSettingsRoute,
  ContractorWorkerDetailsRoute: ContractorWorkerDetailsRoute,
  ContractorWorkersRoute: ContractorWorkersRoute,
  ContractorIndexRoute: ContractorIndexRoute,
  ContractorApplicationsApplicationIdRoute:
    ContractorApplicationsApplicationIdRoute,
  ContractorApplicationsDeclinedRoute: ContractorApplicationsDeclinedRoute,
  ContractorApplicationsHiredRoute: ContractorApplicationsHiredRoute,
  ContractorApplicationsIndexRoute: ContractorApplicationsIndexRoute,
  ContractorJobsJobIdManageRoute: ContractorJobsJobIdManageRoute,
}

const ContractorRouteWithChildren = ContractorRoute._addFileChildren(
  ContractorRouteChildren,
)

interface WorkerEarningsRouteChildren {
  WorkerEarningsCompletedRoute: typeof WorkerEarningsCompletedRoute
  WorkerEarningsMonthlyRoute: typeof WorkerEarningsMonthlyRoute
  WorkerEarningsPendingRoute: typeof WorkerEarningsPendingRoute
  WorkerEarningsTotalRoute: typeof WorkerEarningsTotalRoute
}

const WorkerEarningsRouteChildren: WorkerEarningsRouteChildren = {
  WorkerEarningsCompletedRoute: WorkerEarningsCompletedRoute,
  WorkerEarningsMonthlyRoute: WorkerEarningsMonthlyRoute,
  WorkerEarningsPendingRoute: WorkerEarningsPendingRoute,
  WorkerEarningsTotalRoute: WorkerEarningsTotalRoute,
}

const WorkerEarningsRouteWithChildren = WorkerEarningsRoute._addFileChildren(
  WorkerEarningsRouteChildren,
)

interface WorkerJobsJobIdRouteChildren {
  WorkerJobsJobIdApplyRoute: typeof WorkerJobsJobIdApplyRoute
  WorkerJobsJobIdIndexRoute: typeof WorkerJobsJobIdIndexRoute
}

const WorkerJobsJobIdRouteChildren: WorkerJobsJobIdRouteChildren = {
  WorkerJobsJobIdApplyRoute: WorkerJobsJobIdApplyRoute,
  WorkerJobsJobIdIndexRoute: WorkerJobsJobIdIndexRoute,
}

const WorkerJobsJobIdRouteWithChildren = WorkerJobsJobIdRoute._addFileChildren(
  WorkerJobsJobIdRouteChildren,
)

interface WorkerRouteChildren {
  WorkerAcceptedRoute: typeof WorkerAcceptedRoute
  WorkerChangePasswordRoute: typeof WorkerChangePasswordRoute
  WorkerEarningsRoute: typeof WorkerEarningsRouteWithChildren
  WorkerHelpRoute: typeof WorkerHelpRoute
  WorkerHistoryRoute: typeof WorkerHistoryRoute
  WorkerMessagesRoute: typeof WorkerMessagesRoute
  WorkerNotificationsRoute: typeof WorkerNotificationsRoute
  WorkerPrivacyRoute: typeof WorkerPrivacyRoute
  WorkerProfileRoute: typeof WorkerProfileRoute
  WorkerSettingsRoute: typeof WorkerSettingsRoute
  WorkerIndexRoute: typeof WorkerIndexRoute
  WorkerJobsJobIdRoute: typeof WorkerJobsJobIdRouteWithChildren
  WorkerJobsIndexRoute: typeof WorkerJobsIndexRoute
}

const WorkerRouteChildren: WorkerRouteChildren = {
  WorkerAcceptedRoute: WorkerAcceptedRoute,
  WorkerChangePasswordRoute: WorkerChangePasswordRoute,
  WorkerEarningsRoute: WorkerEarningsRouteWithChildren,
  WorkerHelpRoute: WorkerHelpRoute,
  WorkerHistoryRoute: WorkerHistoryRoute,
  WorkerMessagesRoute: WorkerMessagesRoute,
  WorkerNotificationsRoute: WorkerNotificationsRoute,
  WorkerPrivacyRoute: WorkerPrivacyRoute,
  WorkerProfileRoute: WorkerProfileRoute,
  WorkerSettingsRoute: WorkerSettingsRoute,
  WorkerIndexRoute: WorkerIndexRoute,
  WorkerJobsJobIdRoute: WorkerJobsJobIdRouteWithChildren,
  WorkerJobsIndexRoute: WorkerJobsIndexRoute,
}

const WorkerRouteWithChildren =
  WorkerRoute._addFileChildren(WorkerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthChoiceRoute: AuthChoiceRoute,
  ContractorRoute: ContractorRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  LoginChoiceRoute: LoginChoiceRoute,
  RegisterRoute: RegisterRoute,
  SignupRoute: SignupRoute,
  WelcomeRoute: WelcomeRoute,
  WorkerRoute: WorkerRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
