name: JobNow Load Test Report

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  upload-load-test-report:
    name: '📄 Upload Load Test Report'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Upload Load Test Excel Report
        uses: actions/upload-artifact@v4
        with:
          name: JobNow-Load-Test-Report
          path: "Load Test Results/Load_Test_Report.xlsx"
